import Head from "next/head";
import Image from "next/image";
// import styled from "@emotion/styled";

interface IProps {
  title: string;
  pageTitle: string;
  children: any;
}

export default function layout({ title, pageTitle, children }: IProps) {
  return (
    <>
      <Head>
        <title>{title} | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&display=swap"
        />
      </Head>
        {children}
    </>
  );
}
